# Generated by Django 4.2.1 on 2023-08-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmsslider',
            options={'verbose_name': 'слайд', 'verbose_name_plural': 'Слайды'},
        ),
    ]
